--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 19/09/2019 11.15.11
-- Server version: 5.5.5-10.2.8-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE bpsdmdja_eproper;

--
-- Drop table `rtl`
--
DROP TABLE IF EXISTS rtl;

--
-- Set default database
--
USE bpsdmdja_eproper;

--
-- Create table `rtl`
--
CREATE TABLE rtl (
  id_rtl INT(11) NOT NULL AUTO_INCREMENT,
  nip VARCHAR(64) NOT NULL,
  namadiklat VARCHAR(255) NOT NULL,
  jenisdiklat VARCHAR(64) NOT NULL,
  tahun YEAR(4) NOT NULL,
  ruanglingkup VARCHAR(64) NOT NULL,
  cluster VARCHAR(64) NOT NULL,
  judul VARCHAR(255) NOT NULL,
  latarbelakang LONGTEXT NOT NULL,
  manfaat LONGTEXT NOT NULL,
  milestone LONGTEXT NOT NULL,
  status TINYINT(1) NOT NULL,
  tglsubmit DATETIME NOT NULL,
  tglveri DATETIME DEFAULT NULL,
  asalpeserta VARCHAR(32) NOT NULL,
  PRIMARY KEY (id_rtl)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 8192,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;